name: Déploiement GitHub Pages

on:
  push:
    branches: [ main ]  # le workflow se déclenche quand tu pushes sur main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload du site
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # on déploie tout le dossier racine

      - name: Déploiement vers GitHub Pages
        uses: actions/deploy-pages@v4
